In [2]:
import numpy as np

# Define the matrix to be diagonalized
A = np.array([[2, 1, 3],
              [1, 3 ,5] ,
              [2, 3, 7]])

# Calculate the eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# Diagonalize the matrix
D = np.diag(eigenvalues)
P = eigenvectors

# Verify the diagonalization
A_reconstructed = np.dot(np.dot(P, D), np.linalg.inv(P))

# Print the original matrix, diagonal matrix, and similarity matrix
print("Original Matrix A:")
print(A)
print("\nDiagonal Matrix D:")
print(D)
print("\nSimilarity Matrix P:")
print(P)

# Verify the diagonalization
print("\nVerification (A_reconstructed):")
print(A_reconstructed)


Original Matrix A:
[[2 1 3]
 [1 3 5]
 [2 3 7]]

Diagonal Matrix D:
[[10.19387514  0.          0.        ]
 [ 0.          1.3794373   0.        ]
 [ 0.          0.          0.42668755]]

Similarity Matrix P:
[[-0.34323612 -0.80212372 -0.42805484]
 [-0.56775601  0.59625481 -0.76588364]
 [-0.74822595 -0.03282892  0.47978255]]

Verification (A_reconstructed):
[[2. 1. 3.]
 [1. 3. 5.]
 [2. 3. 7.]]
