In [6]:
import numpy as np
import scipy.linalg as la

# Define your matrix
matrix = np.array([[12, 1, 4],
                   [1, 5.5, 400],
                   [7, 6.8, 5]])

# Perform LU decomposition
P, L, U = la.lu(matrix)

# Print the results
print("Original Matrix:")
print(matrix)
print("\nP (permutation matrix):")
print(P)
print("\nL (lower triangular matrix):")
print(L)
print("\nU (upper triangular matrix):")
print(U)

# Reconstruct the original matrix to verify correctness
matrix_reconstructed = np.dot(P, np.dot(L, U))
print("\nReconstructed Matrix (P * L * U):")
print(matrix_reconstructed)


Original Matrix:
[[ 12.    1.    4. ]
 [  1.    5.5 400. ]
 [  7.    6.8   5. ]]

P (permutation matrix):
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]

L (lower triangular matrix):
[[1.         0.         0.        ]
 [0.58333333 1.         0.        ]
 [0.08333333 0.87131367 1.        ]]

U (upper triangular matrix):
[[ 12.           1.           4.        ]
 [  0.           6.21666667   2.66666667]
 [  0.           0.         397.34316354]]

Reconstructed Matrix (P * L * U):
[[ 12.    1.    4. ]
 [  1.    5.5 400. ]
 [  7.    6.8   5. ]]
