In [1]:
import numpy as np

# Define your matrix
matrix = np.array([[0.0, 2.0, 3.0],
                   [4.0, 5.0, 6.0],
                   [7.0, 8.0, 9.0]])

# Number of rows and columns
n = matrix.shape[0]

# Initialize permutation matrix
P = np.identity(n)

for i in range(n):
    # Find the row with the maximum absolute value in the current column
    max_row = i + np.argmax(np.abs(matrix[i:, i]))
    
    # Swap the rows in the original matrix and the permutation matrix
    matrix[[i, max_row]] = matrix[[max_row, i]]
    P[[i, max_row]] = P[[max_row, i]]

# Print the original matrix and the permutation matrix
print("Original Matrix:")
print(matrix)
print("\nPermutation Matrix:")
print(P)


Original Matrix:
[[7. 8. 9.]
 [4. 5. 6.]
 [0. 2. 3.]]

Permutation Matrix:
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
